### ISSUE TITLE
Failed to load library "macro.ndll"

### ISSUE THREAD

**Issue by DigiEggz** [back2dos/no-spoon#3]
When trying to run a basic `no.Spoon.bend()` example, I receive the following error when targeting Neko:

```
> Called from Main::new line 24
> Called from no.Spoon::bend line 36
> Called from haxe.macro.Context::onAfterGenerate line 370
> Called from haxe.macro.Context::load line 629
> Called from neko.Lib::load line 35
> Uncaught exception - load.c(237) : Failed to load library : macro.ndll
```

When targeting Windows, I instead receive this error:

```
C:/HaxeToolkit/haxe/lib/no-spoon/0,2,0/src/no/Spoon.hx:36: characters 15-30 : Class<haxe.macro.Context> has no field onAfterGenerate
C:/HaxeToolkit/haxe/lib/no-spoon/0,2,0/src/no/Spoon.hx:39: characters 14-31 : Class<haxe.macro.Compiler> has no field addGlobalMetadata
C:/HaxeToolkit/haxe/lib/no-spoon/0,2,0/src/no/Spoon.hx:13: characters 26-40 : Class<haxe.macro.Context> has no field getBuildFields
C:/HaxeToolkit/haxe/lib/no-spoon/0,2,0/src/no/Spoon.hx:14: characters 23-36 : Class<haxe.macro.Context> has no field getLocalClass
C:/HaxeToolkit/haxe/lib/no-spoon/0,2,0/src/no/Spoon.hx:23: characters 13-23 : Class<haxe.macro.Context> has no field defineType
```

**Comment by back2dos** [comment]
Should probably clarify in the doc, but you need to call `no.Spoon.bend` in a macro, ideally an init macro via `--macro` compiler argument. See https://github.com/back2dos/no-spoon/blob/master/tests.hxml#L4 which calls https://github.com/back2dos/no-spoon/blob/master/tests/Modify.hx#L2

**Comment by DigiEggz** [comment]
I figured I was missing something. That helps a bit.

Is it possible to replace a class function that has `super()` calls? I'm trying to replace a new() function, but struggling to wrap my head around it; I just get errors about the class having no super() class.

**Comment by back2dos** [comment]
Yep, that should work. Please provide a minimal example to replicate the problems you're facing.

**Comment by DigiEggz** [comment]
There's a text x/y misalignment issue with a class called [FlxText](https://github.com/HaxeFlixel/flixel/blob/master/flixel/text/FlxText.hx) between desktop and web versions. I wanted to manually adjust text during creation instead of having to do dozens and dozen of class overrides since many classes use FlxText behind the scenes.

I was able to get a few different test examples running so I know things are setup correctly. However, I want to replace code as follows:

```
no.Spoon.bend('flixel.text.FlxText', macro class
{
  public function new(X:Float = 0, Y:Float = 0, FieldWidth:Float = 0, ?Text:String, Size:Int = 8, EmbeddedFont:Bool = true)
{
        // New code here!
	#if desktop
	  super(X - 5, Y - 2);
	#else
	  super(X, Y);
	#end
	// End new code

		if (Text == null || Text == "")
		{
			// empty texts have a textHeight of 0, need to
			// prevent initializing with "" before the first calcFrame() call
			text = "";
			Text = " ";
		}
		else
		{
			text = Text;
		}

		textField = new TextField();
		textField.selectable = false;
		textField.multiline = true;
		textField.wordWrap = true;
		_defaultFormat = new TextFormat(null, Size, 0xffffff);
		font = FlxAssets.FONT_DEFAULT;
		_formatAdjusted = new TextFormat();
		textField.defaultTextFormat = _defaultFormat;
		textField.text = Text;
		fieldWidth = FieldWidth;
		textField.embedFonts = EmbeddedFont;
		textField.sharpness = 100;
		textField.height = (Text.length <= 0) ? 1 : 10;

		allowCollisions = NONE;
		moves = false;

		drawFrame();

		shadowOffset = FlxPoint.get(1, 1); 
}
});
```
My goal is to replace FlxText's `new()` with a version that uses a compiler conditional on the super (X, Y) function to manually adjust the placement. However, I get errors about the other variables too, such as "text" and "textField" missing. I'm not if what I want to do is possible or how to do it properly.
